from app.graph.prompts.brainstorm import (
    DEBATE_SPEAK_SYSTEM,
    DEBATER_RESEARCH_SYSTEM,
    MODERATOR_PROMPT,
    PREPARE_PROMPT,
    ROLE_ORIENTATION,
    WRITER_PROMPT,
)

__all__ = ["DEBATE_SPEAK_SYSTEM", "DEBATER_RESEARCH_SYSTEM", "MODERATOR_PROMPT",
           "PREPARE_PROMPT", "ROLE_ORIENTATION", "WRITER_PROMPT"]


from app.graph.prompts.seminar import (
    ANSWER_SYSTEM, ASK_SYSTEM, CHAIR_INSIGHT_PROMPT, CURATE_PROMPT,
    IMPROVE_SYSTEM, MERGE_PROMPT, NOTE_TEMPLATES, PRESENT_SYSTEM,
    PROPOSE_SYSTEM, RAPPORTEUR_PROMPT, READING_SYSTEM, SCHOLAR_ORIENTATION,
    SCORE_SYSTEM,
)

__all__ += ["ANSWER_SYSTEM", "ASK_SYSTEM", "CHAIR_INSIGHT_PROMPT",
            "CURATE_PROMPT", "IMPROVE_SYSTEM", "MERGE_PROMPT",
            "NOTE_TEMPLATES", "PRESENT_SYSTEM", "PROPOSE_SYSTEM",
            "RAPPORTEUR_PROMPT", "READING_SYSTEM", "SCHOLAR_ORIENTATION",
            "SCORE_SYSTEM"]
